name: Build recall

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            echo There is no test file, skipping
          fi
  # Push image to GitHub Package Registry.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v1

      - name: Log into registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build image
        run: docker build . --file Dockerfile --tag image

      - name: Push image
        run: |
          IMAGE_ID=${{ secrets.REGISTRY_URL }}/$IMAGE_NAME
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  hook:
    needs: push

    runs-on: ubuntu-latest

    steps:
      - name: Send webhook
        uses: swinton/httpie.action@master
        with:
          args: {{ secrets.REFRESHER_URL }}/refresh/${{ secrets.IMAGE_NAME }}?token=${{ secrets.WH_TOKEN }}
  notify:
    needs: push

    runs-on: ubuntu-latest

    steps:
      - name: Send tg message to unclefeudor
        uses: xinthink/action-telegram@v1
        with:
          chatId: ${{ secrets.TELEGRAM_CHAT_ID }}
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          jobStatus: ${{ job.status }}
          skipSuccess: "false"
